### ISSUE TITLE
No rich presence

### ISSUE THREAD

**Issue by dilanx** [nickofolas/discord-rich-presence#11]
Hey, I'm working on a [Tauri](https://tauri.app) app and am trying to connect to Discord RP. I'm literally brand new to rust but here's how I did it:

```
fn main() {
    tauri::Builder::default()
        .setup(|app| {
            let id = app.listen_global("discord", |event| {
                discord();
            });
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}

fn discord() -> Result<(), Box<dyn std::error::Error>> {
    let mut client = DiscordIpcClient::new("my_app_id")?;

    client.connect()?;
    client.set_activity(activity::Activity::new()
        .state("foo")
        .details("bar")
    )?;
    client.close()?;

    println!("test");

    Ok(())
}
```

When I call the `discord()` function, "test" prints but my rich presence doesn't appear on Discord. Any idea what I'm doing wrong?

**Comment by nickofolas** [comment]
Have you tried removing the call to `.close()` that comes immediately after you set the activity?

**Comment by dilanx** [comment]
Yeah. It's odd that it doesn't work here because it does work with [discord-rpc-client](https://crates.io/crates/discord-rpc-client), which I'm now using.

**Comment by nickofolas** [comment]
Odd. What platform is this on?

**Comment by dilanx** [comment]
macOS

**Comment by nickofolas** [comment]
Gotcha. It is _possible_ that it may be an issue with Discord (and may be solved by a client reload), but I'm unsure given that you said it's working with other libs. I've not seen this behavior before, so I'm not really sure as to what else could be causing it, sorry :/

**Comment by dilanx** [comment]
Np, I'll let you know if I get it fixed. Thanks!

**Comment by dilanx** [comment]
Okay so I've figured out that [discord-rpc-client](https://crates.io/crates/discord-rpc-client) works correctly on macOS but is kinda glitchy on Windows (rich presence clears itself after 30-60 seconds) but this package didn't really work for me on macOS but works correctly on Windows. My solution for now is to use both packages platform independently haha it's a bit scuffed but it works. Just sharing this here in case anyone else runs into the same problem.

**Comment by nickofolas** [comment]
Thanks for the update! I'll put in some work on macOS when I get the chance to test on it haha. Glad you got it figured out on your end.
