### ISSUE TITLE
Activity Buttons break Rich Presence

### ISSUE THREAD

**Issue by afonsojramos** [nickofolas/discord-rich-presence#6]
Maybe this is now unsupported by [Discord's API](https://discord.com/developers/docs/rich-presence/how-to), but sending buttons in the Activity struct somehow makes Discord ignore what is sent.

Additionally, the set_activity function does not return any error, which is why I assume that it is simply being ignored.

**Comment by nickofolas** [comment]
I have to imagine this is an issue with your usage - running the `test_models` test works perfectly fine on my end: 
![image](https://user-images.githubusercontent.com/60761231/152719402-0fa598be-1d5c-4440-a07c-ef2a99c9141d.png)

**Comment by nickofolas** [comment]
When you say it doesn't work on MacOS, do you mean the buttons don't show up at all, or something else?

**Comment by afonsojramos** [comment]
When you click the buttons, nothing happens 🤷  This is on a M1 Mac, not sure if it is related.

**Comment by afonsojramos** [comment]
But I suppose this is a Discord issue, so I'll close this.

**Comment by nickofolas** [comment]
Yep, buttons on your own rich presence can't be clicked, for Discord reasons :+1:
