### ISSUE TITLE
Implementation of ActivityType Enum

### ISSUE THREAD

**Issue by afonsojramos** [nickofolas/discord-rich-presence#7]
The ActivityType enum is present in the SDK Docs and, even if it says "ActivityType [...] will be discarded and will not change anything in the client." I can find cases online where such has been said to be possible ([here](https://stackoverflow.com/questions/59126137/how-to-change-discord-py-bot-activity)).

Has this been changed recently? Would it be possible to have this implemented?

<img width="1261" alt="image" src="https://user-images.githubusercontent.com/19473034/167017112-df78cdeb-84d5-4ab5-af0a-990cc01e61da.png">

**Comment by nickofolas** [comment]
What would this be useful for? I did some brief testing and found that, if provided anything other than `0` or `3`, the payload is actually rejected with an error. Furthermore, providing `3` results in the `type` being changed to `0` anyways.

I'm happy to oblige if I can understand the use case, but right now, I don't see the point.

**Comment by afonsojramos** [comment]
In my view, this would be useful just as another way of customising what is displayed in Discord. I have build a Rich Presence for Trakt (https://github.com/afonsojramos/discrakt/) which enables integration with all the services that Trakt is able to connect to, such as all of the ones below:
<img width="848" alt="image" src="https://user-images.githubusercontent.com/19473034/167295527-f4a1299a-6ad6-4ca5-a21c-f61e9ff9e906.png">

As this is for TV/Movies, the "Watching" verb would apply much more than the "Playing" one does!

**Comment by nickofolas** [comment]
I see where you're coming from now - the issue is that it won't work. As stated in my previous comment, Discord does not let rich presence applications change their `ActivityType`; it will always be `Playing`.

**Comment by afonsojramos** [comment]
But you mentioned that it could be `0` or `3`, which is already better than just the current `0`, wouldn't you say?

**Comment by nickofolas** [comment]
I said it could be `0` or `3`, but I also said passing `3` is changed to `0` by Discord when the request is received.

Regardless of whether `0` or `3` is sent, it's treated as a `0` by Discord, so it makes no difference.

**Comment by afonsojramos** [comment]
Oh well, that's unfortunate, thanks anyway!

**Comment by wxllow** [comment]
[Discord supports setting additional activity types now!](https://github.com/discord/discord-api-docs/blob/main/docs/Change_Log.md#supported-activity-types-for-set_activity)
