### ISSUE TITLE
Dynamic LargeImage

### ISSUE THREAD

**Issue by afonsojramos** [nickofolas/discord-rich-presence#8]
Apparently, the `large_image` asset can be an URL, as it can be observed in [PreMiD](https://github.com/PreMiD/Presences/blob/main/websites/N/Netflix/presence.ts#L262), however, I have not been able to replicate it with this library, any idea why?

I have been testing it in my branch [here](https://github.com/afonsojramos/discrakt/blob/25-suggestion-dynamic-image/src/discord.rs#L87), and even though it prints a supposedly valid image (square) in my logging, Discord just ignores it... Any idea why?

<img width="683" alt="image" src="https://user-images.githubusercontent.com/19473034/167023291-d2c87cec-9d5d-4195-8d83-0aa5bd4c3a52.png">

> [image link](https://imdb-api.com/posters/s470/pJEMXgyI0iKAgHwGq8lPXVu2NeT.jpg)

**Comment by nickofolas** [comment]
I can't reproduce this. The image appears without issue.

![image](https://user-images.githubusercontent.com/60761231/167026601-c1e92b15-f97a-4e68-9e88-79baa4fb27d2.png)

Is it possible that you're running into client-side or caching issues?

**Comment by afonsojramos** [comment]
Well, found that it had to do with a redirect from the original link... 

I was sending this: https://imdb-api.com/posters/s470/ckLLIsNy3Z0Go1PYHA2PHzVymUA.jpg
Instead of this: https://image.tmdb.org/t/p/w470_and_h470_face/ckLLIsNy3Z0Go1PYHA2PHzVymUA.jpg

Thank you!
